// Code generated by go-swagger; DO NOT EDIT.

package ftp_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// DeleteFtpusersNameReader is a Reader for the DeleteFtpusersName structure.
type DeleteFtpusersNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFtpusersNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFtpusersNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteFtpusersNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteFtpusersNameOK creates a DeleteFtpusersNameOK with default headers values
func NewDeleteFtpusersNameOK() *DeleteFtpusersNameOK {
	return &DeleteFtpusersNameOK{}
}

/* DeleteFtpusersNameOK describes a response with status code 200, with default header values.

OK
*/
type DeleteFtpusersNameOK struct {
	Payload *models.StatusResponse
}

func (o *DeleteFtpusersNameOK) Error() string {
	return fmt.Sprintf("[DELETE /ftpusers/{name}][%d] deleteFtpusersNameOK  %+v", 200, o.Payload)
}
func (o *DeleteFtpusersNameOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *DeleteFtpusersNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFtpusersNameNotFound creates a DeleteFtpusersNameNotFound with default headers values
func NewDeleteFtpusersNameNotFound() *DeleteFtpusersNameNotFound {
	return &DeleteFtpusersNameNotFound{}
}

/* DeleteFtpusersNameNotFound describes a response with status code 404, with default header values.

User is not found
*/
type DeleteFtpusersNameNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFtpusersNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ftpusers/{name}][%d] deleteFtpusersNameNotFound  %+v", 404, o.Payload)
}
func (o *DeleteFtpusersNameNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFtpusersNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
