// Code generated by go-swagger; DO NOT EDIT.

package ftp_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetFtpusersReader is a Reader for the GetFtpusers structure.
type GetFtpusersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFtpusersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFtpusersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetFtpusersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFtpusersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFtpusersOK creates a GetFtpusersOK with default headers values
func NewGetFtpusersOK() *GetFtpusersOK {
	return &GetFtpusersOK{}
}

/* GetFtpusersOK describes a response with status code 200, with default header values.

OK
*/
type GetFtpusersOK struct {
	Payload []*models.FtpUser
}

func (o *GetFtpusersOK) Error() string {
	return fmt.Sprintf("[GET /ftpusers][%d] getFtpusersOK  %+v", 200, o.Payload)
}
func (o *GetFtpusersOK) GetPayload() []*models.FtpUser {
	return o.Payload
}

func (o *GetFtpusersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFtpusersBadRequest creates a GetFtpusersBadRequest with default headers values
func NewGetFtpusersBadRequest() *GetFtpusersBadRequest {
	return &GetFtpusersBadRequest{}
}

/* GetFtpusersBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type GetFtpusersBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetFtpusersBadRequest) Error() string {
	return fmt.Sprintf("[GET /ftpusers][%d] getFtpusersBadRequest  %+v", 400, o.Payload)
}
func (o *GetFtpusersBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFtpusersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFtpusersNotFound creates a GetFtpusersNotFound with default headers values
func NewGetFtpusersNotFound() *GetFtpusersNotFound {
	return &GetFtpusersNotFound{}
}

/* GetFtpusersNotFound describes a response with status code 404, with default header values.

Domain/user is not found
*/
type GetFtpusersNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetFtpusersNotFound) Error() string {
	return fmt.Sprintf("[GET /ftpusers][%d] getFtpusersNotFound  %+v", 404, o.Payload)
}
func (o *GetFtpusersNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFtpusersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
