// Code generated by go-swagger; DO NOT EDIT.

package ftp_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostFtpusersParams creates a new PostFtpusersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostFtpusersParams() *PostFtpusersParams {
	return &PostFtpusersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostFtpusersParamsWithTimeout creates a new PostFtpusersParams object
// with the ability to set a timeout on a request.
func NewPostFtpusersParamsWithTimeout(timeout time.Duration) *PostFtpusersParams {
	return &PostFtpusersParams{
		timeout: timeout,
	}
}

// NewPostFtpusersParamsWithContext creates a new PostFtpusersParams object
// with the ability to set a context for a request.
func NewPostFtpusersParamsWithContext(ctx context.Context) *PostFtpusersParams {
	return &PostFtpusersParams{
		Context: ctx,
	}
}

// NewPostFtpusersParamsWithHTTPClient creates a new PostFtpusersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostFtpusersParamsWithHTTPClient(client *http.Client) *PostFtpusersParams {
	return &PostFtpusersParams{
		HTTPClient: client,
	}
}

/* PostFtpusersParams contains all the parameters to send to the API endpoint
   for the post ftpusers operation.

   Typically these are written to a http.Request.
*/
type PostFtpusersParams struct {

	/* Body.

	   FTP User data
	*/
	Body *models.FtpUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post ftpusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFtpusersParams) WithDefaults() *PostFtpusersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post ftpusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFtpusersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post ftpusers params
func (o *PostFtpusersParams) WithTimeout(timeout time.Duration) *PostFtpusersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ftpusers params
func (o *PostFtpusersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ftpusers params
func (o *PostFtpusersParams) WithContext(ctx context.Context) *PostFtpusersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ftpusers params
func (o *PostFtpusersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ftpusers params
func (o *PostFtpusersParams) WithHTTPClient(client *http.Client) *PostFtpusersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ftpusers params
func (o *PostFtpusersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post ftpusers params
func (o *PostFtpusersParams) WithBody(body *models.FtpUserRequest) *PostFtpusersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post ftpusers params
func (o *PostFtpusersParams) SetBody(body *models.FtpUserRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostFtpusersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
