// Code generated by go-swagger; DO NOT EDIT.

package ftp_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPutFtpusersNameParams creates a new PutFtpusersNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutFtpusersNameParams() *PutFtpusersNameParams {
	return &PutFtpusersNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutFtpusersNameParamsWithTimeout creates a new PutFtpusersNameParams object
// with the ability to set a timeout on a request.
func NewPutFtpusersNameParamsWithTimeout(timeout time.Duration) *PutFtpusersNameParams {
	return &PutFtpusersNameParams{
		timeout: timeout,
	}
}

// NewPutFtpusersNameParamsWithContext creates a new PutFtpusersNameParams object
// with the ability to set a context for a request.
func NewPutFtpusersNameParamsWithContext(ctx context.Context) *PutFtpusersNameParams {
	return &PutFtpusersNameParams{
		Context: ctx,
	}
}

// NewPutFtpusersNameParamsWithHTTPClient creates a new PutFtpusersNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutFtpusersNameParamsWithHTTPClient(client *http.Client) *PutFtpusersNameParams {
	return &PutFtpusersNameParams{
		HTTPClient: client,
	}
}

/* PutFtpusersNameParams contains all the parameters to send to the API endpoint
   for the put ftpusers name operation.

   Typically these are written to a http.Request.
*/
type PutFtpusersNameParams struct {

	/* Body.

	   FTP User data
	*/
	Body *models.FtpUserUpdateRequest

	/* Name.

	   FTP user name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put ftpusers name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutFtpusersNameParams) WithDefaults() *PutFtpusersNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put ftpusers name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutFtpusersNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put ftpusers name params
func (o *PutFtpusersNameParams) WithTimeout(timeout time.Duration) *PutFtpusersNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put ftpusers name params
func (o *PutFtpusersNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put ftpusers name params
func (o *PutFtpusersNameParams) WithContext(ctx context.Context) *PutFtpusersNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put ftpusers name params
func (o *PutFtpusersNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put ftpusers name params
func (o *PutFtpusersNameParams) WithHTTPClient(client *http.Client) *PutFtpusersNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put ftpusers name params
func (o *PutFtpusersNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put ftpusers name params
func (o *PutFtpusersNameParams) WithBody(body *models.FtpUserUpdateRequest) *PutFtpusersNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put ftpusers name params
func (o *PutFtpusersNameParams) SetBody(body *models.FtpUserUpdateRequest) {
	o.Body = body
}

// WithName adds the name to the put ftpusers name params
func (o *PutFtpusersNameParams) WithName(name string) *PutFtpusersNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put ftpusers name params
func (o *PutFtpusersNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutFtpusersNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
