// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServerIpsParams creates a new GetServerIpsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetServerIpsParams() *GetServerIpsParams {
	return &GetServerIpsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetServerIpsParamsWithTimeout creates a new GetServerIpsParams object
// with the ability to set a timeout on a request.
func NewGetServerIpsParamsWithTimeout(timeout time.Duration) *GetServerIpsParams {
	return &GetServerIpsParams{
		timeout: timeout,
	}
}

// NewGetServerIpsParamsWithContext creates a new GetServerIpsParams object
// with the ability to set a context for a request.
func NewGetServerIpsParamsWithContext(ctx context.Context) *GetServerIpsParams {
	return &GetServerIpsParams{
		Context: ctx,
	}
}

// NewGetServerIpsParamsWithHTTPClient creates a new GetServerIpsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetServerIpsParamsWithHTTPClient(client *http.Client) *GetServerIpsParams {
	return &GetServerIpsParams{
		HTTPClient: client,
	}
}

/* GetServerIpsParams contains all the parameters to send to the API endpoint
   for the get server ips operation.

   Typically these are written to a http.Request.
*/
type GetServerIpsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get server ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServerIpsParams) WithDefaults() *GetServerIpsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get server ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServerIpsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get server ips params
func (o *GetServerIpsParams) WithTimeout(timeout time.Duration) *GetServerIpsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get server ips params
func (o *GetServerIpsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get server ips params
func (o *GetServerIpsParams) WithContext(ctx context.Context) *GetServerIpsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get server ips params
func (o *GetServerIpsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get server ips params
func (o *GetServerIpsParams) WithHTTPClient(client *http.Client) *GetServerIpsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get server ips params
func (o *GetServerIpsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetServerIpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
