// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostServerInitParams creates a new PostServerInitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostServerInitParams() *PostServerInitParams {
	return &PostServerInitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostServerInitParamsWithTimeout creates a new PostServerInitParams object
// with the ability to set a timeout on a request.
func NewPostServerInitParamsWithTimeout(timeout time.Duration) *PostServerInitParams {
	return &PostServerInitParams{
		timeout: timeout,
	}
}

// NewPostServerInitParamsWithContext creates a new PostServerInitParams object
// with the ability to set a context for a request.
func NewPostServerInitParamsWithContext(ctx context.Context) *PostServerInitParams {
	return &PostServerInitParams{
		Context: ctx,
	}
}

// NewPostServerInitParamsWithHTTPClient creates a new PostServerInitParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostServerInitParamsWithHTTPClient(client *http.Client) *PostServerInitParams {
	return &PostServerInitParams{
		HTTPClient: client,
	}
}

/* PostServerInitParams contains all the parameters to send to the API endpoint
   for the post server init operation.

   Typically these are written to a http.Request.
*/
type PostServerInitParams struct {

	/* Body.

	   Inital setup parameters
	*/
	Body *models.ServerInit

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post server init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServerInitParams) WithDefaults() *PostServerInitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post server init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServerInitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post server init params
func (o *PostServerInitParams) WithTimeout(timeout time.Duration) *PostServerInitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post server init params
func (o *PostServerInitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post server init params
func (o *PostServerInitParams) WithContext(ctx context.Context) *PostServerInitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post server init params
func (o *PostServerInitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post server init params
func (o *PostServerInitParams) WithHTTPClient(client *http.Client) *PostServerInitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post server init params
func (o *PostServerInitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post server init params
func (o *PostServerInitParams) WithBody(body *models.ServerInit) *PostServerInitParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post server init params
func (o *PostServerInitParams) SetBody(body *models.ServerInit) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostServerInitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
