// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostServerLicenseParams creates a new PostServerLicenseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostServerLicenseParams() *PostServerLicenseParams {
	return &PostServerLicenseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostServerLicenseParamsWithTimeout creates a new PostServerLicenseParams object
// with the ability to set a timeout on a request.
func NewPostServerLicenseParamsWithTimeout(timeout time.Duration) *PostServerLicenseParams {
	return &PostServerLicenseParams{
		timeout: timeout,
	}
}

// NewPostServerLicenseParamsWithContext creates a new PostServerLicenseParams object
// with the ability to set a context for a request.
func NewPostServerLicenseParamsWithContext(ctx context.Context) *PostServerLicenseParams {
	return &PostServerLicenseParams{
		Context: ctx,
	}
}

// NewPostServerLicenseParamsWithHTTPClient creates a new PostServerLicenseParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostServerLicenseParamsWithHTTPClient(client *http.Client) *PostServerLicenseParams {
	return &PostServerLicenseParams{
		HTTPClient: client,
	}
}

/* PostServerLicenseParams contains all the parameters to send to the API endpoint
   for the post server license operation.

   Typically these are written to a http.Request.
*/
type PostServerLicenseParams struct {

	/* Body.

	   License key
	*/
	Body *models.ServerLicense

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post server license params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServerLicenseParams) WithDefaults() *PostServerLicenseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post server license params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServerLicenseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post server license params
func (o *PostServerLicenseParams) WithTimeout(timeout time.Duration) *PostServerLicenseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post server license params
func (o *PostServerLicenseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post server license params
func (o *PostServerLicenseParams) WithContext(ctx context.Context) *PostServerLicenseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post server license params
func (o *PostServerLicenseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post server license params
func (o *PostServerLicenseParams) WithHTTPClient(client *http.Client) *PostServerLicenseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post server license params
func (o *PostServerLicenseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post server license params
func (o *PostServerLicenseParams) WithBody(body *models.ServerLicense) *PostServerLicenseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post server license params
func (o *PostServerLicenseParams) SetBody(body *models.ServerLicense) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostServerLicenseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
