// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// DeleteExtensionsIDReader is a Reader for the DeleteExtensionsID structure.
type DeleteExtensionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteExtensionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteExtensionsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteExtensionsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteExtensionsIDOK creates a DeleteExtensionsIDOK with default headers values
func NewDeleteExtensionsIDOK() *DeleteExtensionsIDOK {
	return &DeleteExtensionsIDOK{}
}

/* DeleteExtensionsIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteExtensionsIDOK struct {
	Payload *models.StatusResponse
}

func (o *DeleteExtensionsIDOK) Error() string {
	return fmt.Sprintf("[DELETE /extensions/{id}][%d] deleteExtensionsIdOK  %+v", 200, o.Payload)
}
func (o *DeleteExtensionsIDOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *DeleteExtensionsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteExtensionsIDNotFound creates a DeleteExtensionsIDNotFound with default headers values
func NewDeleteExtensionsIDNotFound() *DeleteExtensionsIDNotFound {
	return &DeleteExtensionsIDNotFound{}
}

/* DeleteExtensionsIDNotFound describes a response with status code 404, with default header values.

Extension is not installed
*/
type DeleteExtensionsIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteExtensionsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /extensions/{id}][%d] deleteExtensionsIdNotFound  %+v", 404, o.Payload)
}
func (o *DeleteExtensionsIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteExtensionsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
