// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetExtensionsReader is a Reader for the GetExtensions structure.
type GetExtensionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExtensionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExtensionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExtensionsOK creates a GetExtensionsOK with default headers values
func NewGetExtensionsOK() *GetExtensionsOK {
	return &GetExtensionsOK{}
}

/* GetExtensionsOK describes a response with status code 200, with default header values.

OK
*/
type GetExtensionsOK struct {
	Payload []*models.Extension
}

func (o *GetExtensionsOK) Error() string {
	return fmt.Sprintf("[GET /extensions][%d] getExtensionsOK  %+v", 200, o.Payload)
}
func (o *GetExtensionsOK) GetPayload() []*models.Extension {
	return o.Payload
}

func (o *GetExtensionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
