// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetExtensionsIDParams creates a new GetExtensionsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetExtensionsIDParams() *GetExtensionsIDParams {
	return &GetExtensionsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetExtensionsIDParamsWithTimeout creates a new GetExtensionsIDParams object
// with the ability to set a timeout on a request.
func NewGetExtensionsIDParamsWithTimeout(timeout time.Duration) *GetExtensionsIDParams {
	return &GetExtensionsIDParams{
		timeout: timeout,
	}
}

// NewGetExtensionsIDParamsWithContext creates a new GetExtensionsIDParams object
// with the ability to set a context for a request.
func NewGetExtensionsIDParamsWithContext(ctx context.Context) *GetExtensionsIDParams {
	return &GetExtensionsIDParams{
		Context: ctx,
	}
}

// NewGetExtensionsIDParamsWithHTTPClient creates a new GetExtensionsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetExtensionsIDParamsWithHTTPClient(client *http.Client) *GetExtensionsIDParams {
	return &GetExtensionsIDParams{
		HTTPClient: client,
	}
}

/* GetExtensionsIDParams contains all the parameters to send to the API endpoint
   for the get extensions ID operation.

   Typically these are written to a http.Request.
*/
type GetExtensionsIDParams struct {

	/* ID.

	   Extension identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get extensions ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExtensionsIDParams) WithDefaults() *GetExtensionsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get extensions ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExtensionsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get extensions ID params
func (o *GetExtensionsIDParams) WithTimeout(timeout time.Duration) *GetExtensionsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get extensions ID params
func (o *GetExtensionsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get extensions ID params
func (o *GetExtensionsIDParams) WithContext(ctx context.Context) *GetExtensionsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get extensions ID params
func (o *GetExtensionsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get extensions ID params
func (o *GetExtensionsIDParams) WithHTTPClient(client *http.Client) *GetExtensionsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get extensions ID params
func (o *GetExtensionsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get extensions ID params
func (o *GetExtensionsIDParams) WithID(id string) *GetExtensionsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get extensions ID params
func (o *GetExtensionsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetExtensionsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
