// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostExtensionsParams creates a new PostExtensionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostExtensionsParams() *PostExtensionsParams {
	return &PostExtensionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostExtensionsParamsWithTimeout creates a new PostExtensionsParams object
// with the ability to set a timeout on a request.
func NewPostExtensionsParamsWithTimeout(timeout time.Duration) *PostExtensionsParams {
	return &PostExtensionsParams{
		timeout: timeout,
	}
}

// NewPostExtensionsParamsWithContext creates a new PostExtensionsParams object
// with the ability to set a context for a request.
func NewPostExtensionsParamsWithContext(ctx context.Context) *PostExtensionsParams {
	return &PostExtensionsParams{
		Context: ctx,
	}
}

// NewPostExtensionsParamsWithHTTPClient creates a new PostExtensionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostExtensionsParamsWithHTTPClient(client *http.Client) *PostExtensionsParams {
	return &PostExtensionsParams{
		HTTPClient: client,
	}
}

/* PostExtensionsParams contains all the parameters to send to the API endpoint
   for the post extensions operation.

   Typically these are written to a http.Request.
*/
type PostExtensionsParams struct {

	/* Body.

	   Installation type and resource
	*/
	Body *models.ExtensionInstallRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post extensions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostExtensionsParams) WithDefaults() *PostExtensionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post extensions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostExtensionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post extensions params
func (o *PostExtensionsParams) WithTimeout(timeout time.Duration) *PostExtensionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post extensions params
func (o *PostExtensionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post extensions params
func (o *PostExtensionsParams) WithContext(ctx context.Context) *PostExtensionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post extensions params
func (o *PostExtensionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post extensions params
func (o *PostExtensionsParams) WithHTTPClient(client *http.Client) *PostExtensionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post extensions params
func (o *PostExtensionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post extensions params
func (o *PostExtensionsParams) WithBody(body *models.ExtensionInstallRequest) *PostExtensionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post extensions params
func (o *PostExtensionsParams) SetBody(body *models.ExtensionInstallRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostExtensionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
