// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PostExtensionsReader is a Reader for the PostExtensions structure.
type PostExtensionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostExtensionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostExtensionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostExtensionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostExtensionsOK creates a PostExtensionsOK with default headers values
func NewPostExtensionsOK() *PostExtensionsOK {
	return &PostExtensionsOK{}
}

/* PostExtensionsOK describes a response with status code 200, with default header values.

Extension successfully installed
*/
type PostExtensionsOK struct {
	Payload *models.StatusResponse
}

func (o *PostExtensionsOK) Error() string {
	return fmt.Sprintf("[POST /extensions][%d] postExtensionsOK  %+v", 200, o.Payload)
}
func (o *PostExtensionsOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PostExtensionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostExtensionsBadRequest creates a PostExtensionsBadRequest with default headers values
func NewPostExtensionsBadRequest() *PostExtensionsBadRequest {
	return &PostExtensionsBadRequest{}
}

/* PostExtensionsBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PostExtensionsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostExtensionsBadRequest) Error() string {
	return fmt.Sprintf("[POST /extensions][%d] postExtensionsBadRequest  %+v", 400, o.Payload)
}
func (o *PostExtensionsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostExtensionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
