// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutExtensionsIDEnableParams creates a new PutExtensionsIDEnableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutExtensionsIDEnableParams() *PutExtensionsIDEnableParams {
	return &PutExtensionsIDEnableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutExtensionsIDEnableParamsWithTimeout creates a new PutExtensionsIDEnableParams object
// with the ability to set a timeout on a request.
func NewPutExtensionsIDEnableParamsWithTimeout(timeout time.Duration) *PutExtensionsIDEnableParams {
	return &PutExtensionsIDEnableParams{
		timeout: timeout,
	}
}

// NewPutExtensionsIDEnableParamsWithContext creates a new PutExtensionsIDEnableParams object
// with the ability to set a context for a request.
func NewPutExtensionsIDEnableParamsWithContext(ctx context.Context) *PutExtensionsIDEnableParams {
	return &PutExtensionsIDEnableParams{
		Context: ctx,
	}
}

// NewPutExtensionsIDEnableParamsWithHTTPClient creates a new PutExtensionsIDEnableParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutExtensionsIDEnableParamsWithHTTPClient(client *http.Client) *PutExtensionsIDEnableParams {
	return &PutExtensionsIDEnableParams{
		HTTPClient: client,
	}
}

/* PutExtensionsIDEnableParams contains all the parameters to send to the API endpoint
   for the put extensions ID enable operation.

   Typically these are written to a http.Request.
*/
type PutExtensionsIDEnableParams struct {

	/* ID.

	   Extension identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put extensions ID enable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutExtensionsIDEnableParams) WithDefaults() *PutExtensionsIDEnableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put extensions ID enable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutExtensionsIDEnableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) WithTimeout(timeout time.Duration) *PutExtensionsIDEnableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) WithContext(ctx context.Context) *PutExtensionsIDEnableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) WithHTTPClient(client *http.Client) *PutExtensionsIDEnableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) WithID(id string) *PutExtensionsIDEnableParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put extensions ID enable params
func (o *PutExtensionsIDEnableParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutExtensionsIDEnableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
