// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutExtensionsIDDisableReader is a Reader for the PutExtensionsIDDisable structure.
type PutExtensionsIDDisableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutExtensionsIDDisableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutExtensionsIDDisableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutExtensionsIDDisableNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutExtensionsIDDisableOK creates a PutExtensionsIDDisableOK with default headers values
func NewPutExtensionsIDDisableOK() *PutExtensionsIDDisableOK {
	return &PutExtensionsIDDisableOK{}
}

/* PutExtensionsIDDisableOK describes a response with status code 200, with default header values.

OK
*/
type PutExtensionsIDDisableOK struct {
	Payload *models.StatusResponse
}

func (o *PutExtensionsIDDisableOK) Error() string {
	return fmt.Sprintf("[PUT /extensions/{id}/disable][%d] putExtensionsIdDisableOK  %+v", 200, o.Payload)
}
func (o *PutExtensionsIDDisableOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PutExtensionsIDDisableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutExtensionsIDDisableNotFound creates a PutExtensionsIDDisableNotFound with default headers values
func NewPutExtensionsIDDisableNotFound() *PutExtensionsIDDisableNotFound {
	return &PutExtensionsIDDisableNotFound{}
}

/* PutExtensionsIDDisableNotFound describes a response with status code 404, with default header values.

Extension is not installed
*/
type PutExtensionsIDDisableNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutExtensionsIDDisableNotFound) Error() string {
	return fmt.Sprintf("[PUT /extensions/{id}/disable][%d] putExtensionsIdDisableNotFound  %+v", 404, o.Payload)
}
func (o *PutExtensionsIDDisableNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutExtensionsIDDisableNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
