// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutExtensionsIDEnableReader is a Reader for the PutExtensionsIDEnable structure.
type PutExtensionsIDEnableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutExtensionsIDEnableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutExtensionsIDEnableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutExtensionsIDEnableNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutExtensionsIDEnableOK creates a PutExtensionsIDEnableOK with default headers values
func NewPutExtensionsIDEnableOK() *PutExtensionsIDEnableOK {
	return &PutExtensionsIDEnableOK{}
}

/* PutExtensionsIDEnableOK describes a response with status code 200, with default header values.

OK
*/
type PutExtensionsIDEnableOK struct {
	Payload *models.StatusResponse
}

func (o *PutExtensionsIDEnableOK) Error() string {
	return fmt.Sprintf("[PUT /extensions/{id}/enable][%d] putExtensionsIdEnableOK  %+v", 200, o.Payload)
}
func (o *PutExtensionsIDEnableOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PutExtensionsIDEnableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutExtensionsIDEnableNotFound creates a PutExtensionsIDEnableNotFound with default headers values
func NewPutExtensionsIDEnableNotFound() *PutExtensionsIDEnableNotFound {
	return &PutExtensionsIDEnableNotFound{}
}

/* PutExtensionsIDEnableNotFound describes a response with status code 404, with default header values.

Extension is not installed
*/
type PutExtensionsIDEnableNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutExtensionsIDEnableNotFound) Error() string {
	return fmt.Sprintf("[PUT /extensions/{id}/enable][%d] putExtensionsIdEnableNotFound  %+v", 404, o.Payload)
}
func (o *PutExtensionsIDEnableNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutExtensionsIDEnableNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
