// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDNSRecordsIDParams creates a new GetDNSRecordsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDNSRecordsIDParams() *GetDNSRecordsIDParams {
	return &GetDNSRecordsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDNSRecordsIDParamsWithTimeout creates a new GetDNSRecordsIDParams object
// with the ability to set a timeout on a request.
func NewGetDNSRecordsIDParamsWithTimeout(timeout time.Duration) *GetDNSRecordsIDParams {
	return &GetDNSRecordsIDParams{
		timeout: timeout,
	}
}

// NewGetDNSRecordsIDParamsWithContext creates a new GetDNSRecordsIDParams object
// with the ability to set a context for a request.
func NewGetDNSRecordsIDParamsWithContext(ctx context.Context) *GetDNSRecordsIDParams {
	return &GetDNSRecordsIDParams{
		Context: ctx,
	}
}

// NewGetDNSRecordsIDParamsWithHTTPClient creates a new GetDNSRecordsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDNSRecordsIDParamsWithHTTPClient(client *http.Client) *GetDNSRecordsIDParams {
	return &GetDNSRecordsIDParams{
		HTTPClient: client,
	}
}

/* GetDNSRecordsIDParams contains all the parameters to send to the API endpoint
   for the get DNS records ID operation.

   Typically these are written to a http.Request.
*/
type GetDNSRecordsIDParams struct {

	/* ID.

	   DNS record ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get DNS records ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSRecordsIDParams) WithDefaults() *GetDNSRecordsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get DNS records ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDNSRecordsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get DNS records ID params
func (o *GetDNSRecordsIDParams) WithTimeout(timeout time.Duration) *GetDNSRecordsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get DNS records ID params
func (o *GetDNSRecordsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get DNS records ID params
func (o *GetDNSRecordsIDParams) WithContext(ctx context.Context) *GetDNSRecordsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get DNS records ID params
func (o *GetDNSRecordsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get DNS records ID params
func (o *GetDNSRecordsIDParams) WithHTTPClient(client *http.Client) *GetDNSRecordsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get DNS records ID params
func (o *GetDNSRecordsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get DNS records ID params
func (o *GetDNSRecordsIDParams) WithID(id int64) *GetDNSRecordsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get DNS records ID params
func (o *GetDNSRecordsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDNSRecordsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
