// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetDomainsIDReader is a Reader for the GetDomainsID structure.
type GetDomainsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDomainsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDomainsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDomainsIDOK creates a GetDomainsIDOK with default headers values
func NewGetDomainsIDOK() *GetDomainsIDOK {
	return &GetDomainsIDOK{}
}

/* GetDomainsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetDomainsIDOK struct {
	Payload *models.DomainResponse
}

func (o *GetDomainsIDOK) Error() string {
	return fmt.Sprintf("[GET /domains/{id}][%d] getDomainsIdOK  %+v", 200, o.Payload)
}
func (o *GetDomainsIDOK) GetPayload() *models.DomainResponse {
	return o.Payload
}

func (o *GetDomainsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DomainResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsIDNotFound creates a GetDomainsIDNotFound with default headers values
func NewGetDomainsIDNotFound() *GetDomainsIDNotFound {
	return &GetDomainsIDNotFound{}
}

/* GetDomainsIDNotFound describes a response with status code 404, with default header values.

Domain is not found
*/
type GetDomainsIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetDomainsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /domains/{id}][%d] getDomainsIdNotFound  %+v", 404, o.Payload)
}
func (o *GetDomainsIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDomainsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
