// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDomainsIDParams creates a new GetDomainsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDomainsIDParams() *GetDomainsIDParams {
	return &GetDomainsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsIDParamsWithTimeout creates a new GetDomainsIDParams object
// with the ability to set a timeout on a request.
func NewGetDomainsIDParamsWithTimeout(timeout time.Duration) *GetDomainsIDParams {
	return &GetDomainsIDParams{
		timeout: timeout,
	}
}

// NewGetDomainsIDParamsWithContext creates a new GetDomainsIDParams object
// with the ability to set a context for a request.
func NewGetDomainsIDParamsWithContext(ctx context.Context) *GetDomainsIDParams {
	return &GetDomainsIDParams{
		Context: ctx,
	}
}

// NewGetDomainsIDParamsWithHTTPClient creates a new GetDomainsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDomainsIDParamsWithHTTPClient(client *http.Client) *GetDomainsIDParams {
	return &GetDomainsIDParams{
		HTTPClient: client,
	}
}

/* GetDomainsIDParams contains all the parameters to send to the API endpoint
   for the get domains ID operation.

   Typically these are written to a http.Request.
*/
type GetDomainsIDParams struct {

	/* ID.

	   Domain ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get domains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainsIDParams) WithDefaults() *GetDomainsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get domains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get domains ID params
func (o *GetDomainsIDParams) WithTimeout(timeout time.Duration) *GetDomainsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains ID params
func (o *GetDomainsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains ID params
func (o *GetDomainsIDParams) WithContext(ctx context.Context) *GetDomainsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains ID params
func (o *GetDomainsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domains ID params
func (o *GetDomainsIDParams) WithHTTPClient(client *http.Client) *GetDomainsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domains ID params
func (o *GetDomainsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get domains ID params
func (o *GetDomainsIDParams) WithID(id int64) *GetDomainsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get domains ID params
func (o *GetDomainsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
