// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetDomainsIDClientReader is a Reader for the GetDomainsIDClient structure.
type GetDomainsIDClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainsIDClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDomainsIDClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDomainsIDClientNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDomainsIDClientOK creates a GetDomainsIDClientOK with default headers values
func NewGetDomainsIDClientOK() *GetDomainsIDClientOK {
	return &GetDomainsIDClientOK{}
}

/* GetDomainsIDClientOK describes a response with status code 200, with default header values.

OK
*/
type GetDomainsIDClientOK struct {
	Payload *models.Client
}

func (o *GetDomainsIDClientOK) Error() string {
	return fmt.Sprintf("[GET /domains/{id}/client][%d] getDomainsIdClientOK  %+v", 200, o.Payload)
}
func (o *GetDomainsIDClientOK) GetPayload() *models.Client {
	return o.Payload
}

func (o *GetDomainsIDClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Client)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainsIDClientNotFound creates a GetDomainsIDClientNotFound with default headers values
func NewGetDomainsIDClientNotFound() *GetDomainsIDClientNotFound {
	return &GetDomainsIDClientNotFound{}
}

/* GetDomainsIDClientNotFound describes a response with status code 404, with default header values.

Domain is not found
*/
type GetDomainsIDClientNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetDomainsIDClientNotFound) Error() string {
	return fmt.Sprintf("[GET /domains/{id}/client][%d] getDomainsIdClientNotFound  %+v", 404, o.Payload)
}
func (o *GetDomainsIDClientNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDomainsIDClientNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
