// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PostDomainsReader is a Reader for the PostDomains structure.
type PostDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostDomainsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDomainsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDomainsCreated creates a PostDomainsCreated with default headers values
func NewPostDomainsCreated() *PostDomainsCreated {
	return &PostDomainsCreated{}
}

/* PostDomainsCreated describes a response with status code 201, with default header values.

Domain successfully created
*/
type PostDomainsCreated struct {
	Payload *models.CreatedResponse
}

func (o *PostDomainsCreated) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsCreated  %+v", 201, o.Payload)
}
func (o *PostDomainsCreated) GetPayload() *models.CreatedResponse {
	return o.Payload
}

func (o *PostDomainsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainsBadRequest creates a PostDomainsBadRequest with default headers values
func NewPostDomainsBadRequest() *PostDomainsBadRequest {
	return &PostDomainsBadRequest{}
}

/* PostDomainsBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PostDomainsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostDomainsBadRequest) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsBadRequest  %+v", 400, o.Payload)
}
func (o *PostDomainsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostDomainsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
