// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutDomainsIDReader is a Reader for the PutDomainsID structure.
type PutDomainsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDomainsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutDomainsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutDomainsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutDomainsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutDomainsIDOK creates a PutDomainsIDOK with default headers values
func NewPutDomainsIDOK() *PutDomainsIDOK {
	return &PutDomainsIDOK{}
}

/* PutDomainsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutDomainsIDOK struct {
	Payload *models.CreatedResponse
}

func (o *PutDomainsIDOK) Error() string {
	return fmt.Sprintf("[PUT /domains/{id}][%d] putDomainsIdOK  %+v", 200, o.Payload)
}
func (o *PutDomainsIDOK) GetPayload() *models.CreatedResponse {
	return o.Payload
}

func (o *PutDomainsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsIDBadRequest creates a PutDomainsIDBadRequest with default headers values
func NewPutDomainsIDBadRequest() *PutDomainsIDBadRequest {
	return &PutDomainsIDBadRequest{}
}

/* PutDomainsIDBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PutDomainsIDBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutDomainsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /domains/{id}][%d] putDomainsIdBadRequest  %+v", 400, o.Payload)
}
func (o *PutDomainsIDBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutDomainsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDomainsIDNotFound creates a PutDomainsIDNotFound with default headers values
func NewPutDomainsIDNotFound() *PutDomainsIDNotFound {
	return &PutDomainsIDNotFound{}
}

/* PutDomainsIDNotFound describes a response with status code 404, with default header values.

Domain is not found
*/
type PutDomainsIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutDomainsIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /domains/{id}][%d] putDomainsIdNotFound  %+v", 404, o.Payload)
}
func (o *PutDomainsIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutDomainsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
