// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/jxsl13/plesgo/models"
)

// NewPutDomainsIDParams creates a new PutDomainsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutDomainsIDParams() *PutDomainsIDParams {
	return &PutDomainsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutDomainsIDParamsWithTimeout creates a new PutDomainsIDParams object
// with the ability to set a timeout on a request.
func NewPutDomainsIDParamsWithTimeout(timeout time.Duration) *PutDomainsIDParams {
	return &PutDomainsIDParams{
		timeout: timeout,
	}
}

// NewPutDomainsIDParamsWithContext creates a new PutDomainsIDParams object
// with the ability to set a context for a request.
func NewPutDomainsIDParamsWithContext(ctx context.Context) *PutDomainsIDParams {
	return &PutDomainsIDParams{
		Context: ctx,
	}
}

// NewPutDomainsIDParamsWithHTTPClient creates a new PutDomainsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutDomainsIDParamsWithHTTPClient(client *http.Client) *PutDomainsIDParams {
	return &PutDomainsIDParams{
		HTTPClient: client,
	}
}

/* PutDomainsIDParams contains all the parameters to send to the API endpoint
   for the put domains ID operation.

   Typically these are written to a http.Request.
*/
type PutDomainsIDParams struct {

	/* Body.

	   Domain
	*/
	Body *models.DomainRequest

	/* ID.

	   Domain ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put domains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDomainsIDParams) WithDefaults() *PutDomainsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put domains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDomainsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put domains ID params
func (o *PutDomainsIDParams) WithTimeout(timeout time.Duration) *PutDomainsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put domains ID params
func (o *PutDomainsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put domains ID params
func (o *PutDomainsIDParams) WithContext(ctx context.Context) *PutDomainsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put domains ID params
func (o *PutDomainsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put domains ID params
func (o *PutDomainsIDParams) WithHTTPClient(client *http.Client) *PutDomainsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put domains ID params
func (o *PutDomainsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put domains ID params
func (o *PutDomainsIDParams) WithBody(body *models.DomainRequest) *PutDomainsIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put domains ID params
func (o *PutDomainsIDParams) SetBody(body *models.DomainRequest) {
	o.Body = body
}

// WithID adds the id to the put domains ID params
func (o *PutDomainsIDParams) WithID(id int64) *PutDomainsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put domains ID params
func (o *PutDomainsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutDomainsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
