// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// DeleteAuthKeysKeyReader is a Reader for the DeleteAuthKeysKey structure.
type DeleteAuthKeysKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAuthKeysKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAuthKeysKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAuthKeysKeyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAuthKeysKeyOK creates a DeleteAuthKeysKeyOK with default headers values
func NewDeleteAuthKeysKeyOK() *DeleteAuthKeysKeyOK {
	return &DeleteAuthKeysKeyOK{}
}

/* DeleteAuthKeysKeyOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAuthKeysKeyOK struct {
	Payload *models.StatusResponse
}

func (o *DeleteAuthKeysKeyOK) Error() string {
	return fmt.Sprintf("[DELETE /auth/keys/{key}][%d] deleteAuthKeysKeyOK  %+v", 200, o.Payload)
}
func (o *DeleteAuthKeysKeyOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *DeleteAuthKeysKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAuthKeysKeyNotFound creates a DeleteAuthKeysKeyNotFound with default headers values
func NewDeleteAuthKeysKeyNotFound() *DeleteAuthKeysKeyNotFound {
	return &DeleteAuthKeysKeyNotFound{}
}

/* DeleteAuthKeysKeyNotFound describes a response with status code 404, with default header values.

Key does not exist
*/
type DeleteAuthKeysKeyNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteAuthKeysKeyNotFound) Error() string {
	return fmt.Sprintf("[DELETE /auth/keys/{key}][%d] deleteAuthKeysKeyNotFound  %+v", 404, o.Payload)
}
func (o *DeleteAuthKeysKeyNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteAuthKeysKeyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
