// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteClientsIDParams creates a new DeleteClientsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteClientsIDParams() *DeleteClientsIDParams {
	return &DeleteClientsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClientsIDParamsWithTimeout creates a new DeleteClientsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteClientsIDParamsWithTimeout(timeout time.Duration) *DeleteClientsIDParams {
	return &DeleteClientsIDParams{
		timeout: timeout,
	}
}

// NewDeleteClientsIDParamsWithContext creates a new DeleteClientsIDParams object
// with the ability to set a context for a request.
func NewDeleteClientsIDParamsWithContext(ctx context.Context) *DeleteClientsIDParams {
	return &DeleteClientsIDParams{
		Context: ctx,
	}
}

// NewDeleteClientsIDParamsWithHTTPClient creates a new DeleteClientsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteClientsIDParamsWithHTTPClient(client *http.Client) *DeleteClientsIDParams {
	return &DeleteClientsIDParams{
		HTTPClient: client,
	}
}

/* DeleteClientsIDParams contains all the parameters to send to the API endpoint
   for the delete clients ID operation.

   Typically these are written to a http.Request.
*/
type DeleteClientsIDParams struct {

	/* ID.

	   Client ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete clients ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClientsIDParams) WithDefaults() *DeleteClientsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete clients ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClientsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete clients ID params
func (o *DeleteClientsIDParams) WithTimeout(timeout time.Duration) *DeleteClientsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete clients ID params
func (o *DeleteClientsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete clients ID params
func (o *DeleteClientsIDParams) WithContext(ctx context.Context) *DeleteClientsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete clients ID params
func (o *DeleteClientsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete clients ID params
func (o *DeleteClientsIDParams) WithHTTPClient(client *http.Client) *DeleteClientsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete clients ID params
func (o *DeleteClientsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete clients ID params
func (o *DeleteClientsIDParams) WithID(id int64) *DeleteClientsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete clients ID params
func (o *DeleteClientsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClientsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
