// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetClientsIDStatisticsParams creates a new GetClientsIDStatisticsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClientsIDStatisticsParams() *GetClientsIDStatisticsParams {
	return &GetClientsIDStatisticsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClientsIDStatisticsParamsWithTimeout creates a new GetClientsIDStatisticsParams object
// with the ability to set a timeout on a request.
func NewGetClientsIDStatisticsParamsWithTimeout(timeout time.Duration) *GetClientsIDStatisticsParams {
	return &GetClientsIDStatisticsParams{
		timeout: timeout,
	}
}

// NewGetClientsIDStatisticsParamsWithContext creates a new GetClientsIDStatisticsParams object
// with the ability to set a context for a request.
func NewGetClientsIDStatisticsParamsWithContext(ctx context.Context) *GetClientsIDStatisticsParams {
	return &GetClientsIDStatisticsParams{
		Context: ctx,
	}
}

// NewGetClientsIDStatisticsParamsWithHTTPClient creates a new GetClientsIDStatisticsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClientsIDStatisticsParamsWithHTTPClient(client *http.Client) *GetClientsIDStatisticsParams {
	return &GetClientsIDStatisticsParams{
		HTTPClient: client,
	}
}

/* GetClientsIDStatisticsParams contains all the parameters to send to the API endpoint
   for the get clients ID statistics operation.

   Typically these are written to a http.Request.
*/
type GetClientsIDStatisticsParams struct {

	/* ID.

	   Client ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get clients ID statistics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClientsIDStatisticsParams) WithDefaults() *GetClientsIDStatisticsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get clients ID statistics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClientsIDStatisticsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) WithTimeout(timeout time.Duration) *GetClientsIDStatisticsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) WithContext(ctx context.Context) *GetClientsIDStatisticsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) WithHTTPClient(client *http.Client) *GetClientsIDStatisticsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) WithID(id int64) *GetClientsIDStatisticsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get clients ID statistics params
func (o *GetClientsIDStatisticsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetClientsIDStatisticsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
