// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetClientsIDReader is a Reader for the GetClientsID structure.
type GetClientsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClientsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClientsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetClientsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetClientsIDOK creates a GetClientsIDOK with default headers values
func NewGetClientsIDOK() *GetClientsIDOK {
	return &GetClientsIDOK{}
}

/* GetClientsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetClientsIDOK struct {
	Payload *models.Client
}

func (o *GetClientsIDOK) Error() string {
	return fmt.Sprintf("[GET /clients/{id}][%d] getClientsIdOK  %+v", 200, o.Payload)
}
func (o *GetClientsIDOK) GetPayload() *models.Client {
	return o.Payload
}

func (o *GetClientsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Client)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClientsIDNotFound creates a GetClientsIDNotFound with default headers values
func NewGetClientsIDNotFound() *GetClientsIDNotFound {
	return &GetClientsIDNotFound{}
}

/* GetClientsIDNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type GetClientsIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetClientsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /clients/{id}][%d] getClientsIdNotFound  %+v", 404, o.Payload)
}
func (o *GetClientsIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetClientsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
