// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetClientsIDDomainsReader is a Reader for the GetClientsIDDomains structure.
type GetClientsIDDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClientsIDDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClientsIDDomainsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetClientsIDDomainsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetClientsIDDomainsOK creates a GetClientsIDDomainsOK with default headers values
func NewGetClientsIDDomainsOK() *GetClientsIDDomainsOK {
	return &GetClientsIDDomainsOK{}
}

/* GetClientsIDDomainsOK describes a response with status code 200, with default header values.

OK
*/
type GetClientsIDDomainsOK struct {
	Payload []*models.DomainResponse
}

func (o *GetClientsIDDomainsOK) Error() string {
	return fmt.Sprintf("[GET /clients/{id}/domains][%d] getClientsIdDomainsOK  %+v", 200, o.Payload)
}
func (o *GetClientsIDDomainsOK) GetPayload() []*models.DomainResponse {
	return o.Payload
}

func (o *GetClientsIDDomainsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClientsIDDomainsNotFound creates a GetClientsIDDomainsNotFound with default headers values
func NewGetClientsIDDomainsNotFound() *GetClientsIDDomainsNotFound {
	return &GetClientsIDDomainsNotFound{}
}

/* GetClientsIDDomainsNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type GetClientsIDDomainsNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetClientsIDDomainsNotFound) Error() string {
	return fmt.Sprintf("[GET /clients/{id}/domains][%d] getClientsIdDomainsNotFound  %+v", 404, o.Payload)
}
func (o *GetClientsIDDomainsNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetClientsIDDomainsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
