// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetClientsIDStatisticsReader is a Reader for the GetClientsIDStatistics structure.
type GetClientsIDStatisticsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClientsIDStatisticsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClientsIDStatisticsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetClientsIDStatisticsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetClientsIDStatisticsOK creates a GetClientsIDStatisticsOK with default headers values
func NewGetClientsIDStatisticsOK() *GetClientsIDStatisticsOK {
	return &GetClientsIDStatisticsOK{}
}

/* GetClientsIDStatisticsOK describes a response with status code 200, with default header values.

OK
*/
type GetClientsIDStatisticsOK struct {
	Payload *models.ClientStatistics
}

func (o *GetClientsIDStatisticsOK) Error() string {
	return fmt.Sprintf("[GET /clients/{id}/statistics][%d] getClientsIdStatisticsOK  %+v", 200, o.Payload)
}
func (o *GetClientsIDStatisticsOK) GetPayload() *models.ClientStatistics {
	return o.Payload
}

func (o *GetClientsIDStatisticsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientStatistics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClientsIDStatisticsNotFound creates a GetClientsIDStatisticsNotFound with default headers values
func NewGetClientsIDStatisticsNotFound() *GetClientsIDStatisticsNotFound {
	return &GetClientsIDStatisticsNotFound{}
}

/* GetClientsIDStatisticsNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type GetClientsIDStatisticsNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetClientsIDStatisticsNotFound) Error() string {
	return fmt.Sprintf("[GET /clients/{id}/statistics][%d] getClientsIdStatisticsNotFound  %+v", 404, o.Payload)
}
func (o *GetClientsIDStatisticsNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetClientsIDStatisticsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
