// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PostClientsReader is a Reader for the PostClients structure.
type PostClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostClientsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostClientsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostClientsCreated creates a PostClientsCreated with default headers values
func NewPostClientsCreated() *PostClientsCreated {
	return &PostClientsCreated{}
}

/* PostClientsCreated describes a response with status code 201, with default header values.

Client account successfully created
*/
type PostClientsCreated struct {
	Payload *models.CreatedResponse
}

func (o *PostClientsCreated) Error() string {
	return fmt.Sprintf("[POST /clients][%d] postClientsCreated  %+v", 201, o.Payload)
}
func (o *PostClientsCreated) GetPayload() *models.CreatedResponse {
	return o.Payload
}

func (o *PostClientsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostClientsBadRequest creates a PostClientsBadRequest with default headers values
func NewPostClientsBadRequest() *PostClientsBadRequest {
	return &PostClientsBadRequest{}
}

/* PostClientsBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PostClientsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostClientsBadRequest) Error() string {
	return fmt.Sprintf("[POST /clients][%d] postClientsBadRequest  %+v", 400, o.Payload)
}
func (o *PostClientsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostClientsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
