// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutClientsIDReader is a Reader for the PutClientsID structure.
type PutClientsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutClientsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutClientsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutClientsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutClientsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutClientsIDOK creates a PutClientsIDOK with default headers values
func NewPutClientsIDOK() *PutClientsIDOK {
	return &PutClientsIDOK{}
}

/* PutClientsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutClientsIDOK struct {
	Payload *models.CreatedResponse
}

func (o *PutClientsIDOK) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}][%d] putClientsIdOK  %+v", 200, o.Payload)
}
func (o *PutClientsIDOK) GetPayload() *models.CreatedResponse {
	return o.Payload
}

func (o *PutClientsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutClientsIDBadRequest creates a PutClientsIDBadRequest with default headers values
func NewPutClientsIDBadRequest() *PutClientsIDBadRequest {
	return &PutClientsIDBadRequest{}
}

/* PutClientsIDBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PutClientsIDBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutClientsIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}][%d] putClientsIdBadRequest  %+v", 400, o.Payload)
}
func (o *PutClientsIDBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutClientsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutClientsIDNotFound creates a PutClientsIDNotFound with default headers values
func NewPutClientsIDNotFound() *PutClientsIDNotFound {
	return &PutClientsIDNotFound{}
}

/* PutClientsIDNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type PutClientsIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutClientsIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}][%d] putClientsIdNotFound  %+v", 404, o.Payload)
}
func (o *PutClientsIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutClientsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
