// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutClientsIDSuspendParams creates a new PutClientsIDSuspendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutClientsIDSuspendParams() *PutClientsIDSuspendParams {
	return &PutClientsIDSuspendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutClientsIDSuspendParamsWithTimeout creates a new PutClientsIDSuspendParams object
// with the ability to set a timeout on a request.
func NewPutClientsIDSuspendParamsWithTimeout(timeout time.Duration) *PutClientsIDSuspendParams {
	return &PutClientsIDSuspendParams{
		timeout: timeout,
	}
}

// NewPutClientsIDSuspendParamsWithContext creates a new PutClientsIDSuspendParams object
// with the ability to set a context for a request.
func NewPutClientsIDSuspendParamsWithContext(ctx context.Context) *PutClientsIDSuspendParams {
	return &PutClientsIDSuspendParams{
		Context: ctx,
	}
}

// NewPutClientsIDSuspendParamsWithHTTPClient creates a new PutClientsIDSuspendParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutClientsIDSuspendParamsWithHTTPClient(client *http.Client) *PutClientsIDSuspendParams {
	return &PutClientsIDSuspendParams{
		HTTPClient: client,
	}
}

/* PutClientsIDSuspendParams contains all the parameters to send to the API endpoint
   for the put clients ID suspend operation.

   Typically these are written to a http.Request.
*/
type PutClientsIDSuspendParams struct {

	/* ID.

	   Client ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put clients ID suspend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutClientsIDSuspendParams) WithDefaults() *PutClientsIDSuspendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put clients ID suspend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutClientsIDSuspendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) WithTimeout(timeout time.Duration) *PutClientsIDSuspendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) WithContext(ctx context.Context) *PutClientsIDSuspendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) WithHTTPClient(client *http.Client) *PutClientsIDSuspendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) WithID(id int64) *PutClientsIDSuspendParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put clients ID suspend params
func (o *PutClientsIDSuspendParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutClientsIDSuspendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
