// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutClientsIDSuspendReader is a Reader for the PutClientsIDSuspend structure.
type PutClientsIDSuspendReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutClientsIDSuspendReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutClientsIDSuspendOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutClientsIDSuspendNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutClientsIDSuspendOK creates a PutClientsIDSuspendOK with default headers values
func NewPutClientsIDSuspendOK() *PutClientsIDSuspendOK {
	return &PutClientsIDSuspendOK{}
}

/* PutClientsIDSuspendOK describes a response with status code 200, with default header values.

OK
*/
type PutClientsIDSuspendOK struct {
	Payload *models.StatusResponse
}

func (o *PutClientsIDSuspendOK) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}/suspend][%d] putClientsIdSuspendOK  %+v", 200, o.Payload)
}
func (o *PutClientsIDSuspendOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PutClientsIDSuspendOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutClientsIDSuspendNotFound creates a PutClientsIDSuspendNotFound with default headers values
func NewPutClientsIDSuspendNotFound() *PutClientsIDSuspendNotFound {
	return &PutClientsIDSuspendNotFound{}
}

/* PutClientsIDSuspendNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type PutClientsIDSuspendNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutClientsIDSuspendNotFound) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}/suspend][%d] putClientsIdSuspendNotFound  %+v", 404, o.Payload)
}
func (o *PutClientsIDSuspendNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutClientsIDSuspendNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
