// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutClientsIDActivateReader is a Reader for the PutClientsIDActivate structure.
type PutClientsIDActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutClientsIDActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutClientsIDActivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPutClientsIDActivateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutClientsIDActivateOK creates a PutClientsIDActivateOK with default headers values
func NewPutClientsIDActivateOK() *PutClientsIDActivateOK {
	return &PutClientsIDActivateOK{}
}

/* PutClientsIDActivateOK describes a response with status code 200, with default header values.

OK
*/
type PutClientsIDActivateOK struct {
	Payload *models.StatusResponse
}

func (o *PutClientsIDActivateOK) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}/activate][%d] putClientsIdActivateOK  %+v", 200, o.Payload)
}
func (o *PutClientsIDActivateOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PutClientsIDActivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutClientsIDActivateNotFound creates a PutClientsIDActivateNotFound with default headers values
func NewPutClientsIDActivateNotFound() *PutClientsIDActivateNotFound {
	return &PutClientsIDActivateNotFound{}
}

/* PutClientsIDActivateNotFound describes a response with status code 404, with default header values.

Client is not found
*/
type PutClientsIDActivateNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutClientsIDActivateNotFound) Error() string {
	return fmt.Sprintf("[PUT /clients/{id}/activate][%d] putClientsIdActivateNotFound  %+v", 404, o.Payload)
}
func (o *PutClientsIDActivateNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutClientsIDActivateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
