// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutClientsIDActivateParams creates a new PutClientsIDActivateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutClientsIDActivateParams() *PutClientsIDActivateParams {
	return &PutClientsIDActivateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutClientsIDActivateParamsWithTimeout creates a new PutClientsIDActivateParams object
// with the ability to set a timeout on a request.
func NewPutClientsIDActivateParamsWithTimeout(timeout time.Duration) *PutClientsIDActivateParams {
	return &PutClientsIDActivateParams{
		timeout: timeout,
	}
}

// NewPutClientsIDActivateParamsWithContext creates a new PutClientsIDActivateParams object
// with the ability to set a context for a request.
func NewPutClientsIDActivateParamsWithContext(ctx context.Context) *PutClientsIDActivateParams {
	return &PutClientsIDActivateParams{
		Context: ctx,
	}
}

// NewPutClientsIDActivateParamsWithHTTPClient creates a new PutClientsIDActivateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutClientsIDActivateParamsWithHTTPClient(client *http.Client) *PutClientsIDActivateParams {
	return &PutClientsIDActivateParams{
		HTTPClient: client,
	}
}

/* PutClientsIDActivateParams contains all the parameters to send to the API endpoint
   for the put clients ID activate operation.

   Typically these are written to a http.Request.
*/
type PutClientsIDActivateParams struct {

	/* ID.

	   Client ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put clients ID activate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutClientsIDActivateParams) WithDefaults() *PutClientsIDActivateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put clients ID activate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutClientsIDActivateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put clients ID activate params
func (o *PutClientsIDActivateParams) WithTimeout(timeout time.Duration) *PutClientsIDActivateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put clients ID activate params
func (o *PutClientsIDActivateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put clients ID activate params
func (o *PutClientsIDActivateParams) WithContext(ctx context.Context) *PutClientsIDActivateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put clients ID activate params
func (o *PutClientsIDActivateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put clients ID activate params
func (o *PutClientsIDActivateParams) WithHTTPClient(client *http.Client) *PutClientsIDActivateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put clients ID activate params
func (o *PutClientsIDActivateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put clients ID activate params
func (o *PutClientsIDActivateParams) WithID(id int64) *PutClientsIDActivateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put clients ID activate params
func (o *PutClientsIDActivateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutClientsIDActivateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
