// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new cli API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cli API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetCliCommands(params *GetCliCommandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCliCommandsOK, error)

	GetCliIDRef(params *GetCliIDRefParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCliIDRefOK, error)

	PostCliIDCall(params *PostCliIDCallParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCliIDCallOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCliCommands lists of available commands
*/
func (a *Client) GetCliCommands(params *GetCliCommandsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCliCommandsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCliCommandsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCliCommands",
		Method:             "GET",
		PathPattern:        "/cli/commands",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCliCommandsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCliCommandsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCliCommands: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCliIDRef commands reference

  plesk: >= 17.9
*/
func (a *Client) GetCliIDRef(params *GetCliIDRefParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCliIDRefOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCliIDRefParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCliIDRef",
		Method:             "GET",
		PathPattern:        "/cli/{id}/ref",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCliIDRefReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCliIDRefOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCliIDRef: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostCliIDCall executes command
*/
func (a *Client) PostCliIDCall(params *PostCliIDCallParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostCliIDCallOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostCliIDCallParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostCliIDCall",
		Method:             "POST",
		PathPattern:        "/cli/{id}/call",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostCliIDCallReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostCliIDCallOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostCliIDCall: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
