// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCliIDRefParams creates a new GetCliIDRefParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCliIDRefParams() *GetCliIDRefParams {
	return &GetCliIDRefParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCliIDRefParamsWithTimeout creates a new GetCliIDRefParams object
// with the ability to set a timeout on a request.
func NewGetCliIDRefParamsWithTimeout(timeout time.Duration) *GetCliIDRefParams {
	return &GetCliIDRefParams{
		timeout: timeout,
	}
}

// NewGetCliIDRefParamsWithContext creates a new GetCliIDRefParams object
// with the ability to set a context for a request.
func NewGetCliIDRefParamsWithContext(ctx context.Context) *GetCliIDRefParams {
	return &GetCliIDRefParams{
		Context: ctx,
	}
}

// NewGetCliIDRefParamsWithHTTPClient creates a new GetCliIDRefParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCliIDRefParamsWithHTTPClient(client *http.Client) *GetCliIDRefParams {
	return &GetCliIDRefParams{
		HTTPClient: client,
	}
}

/* GetCliIDRefParams contains all the parameters to send to the API endpoint
   for the get cli ID ref operation.

   Typically these are written to a http.Request.
*/
type GetCliIDRefParams struct {

	/* ID.

	   Command identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cli ID ref params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCliIDRefParams) WithDefaults() *GetCliIDRefParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cli ID ref params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCliIDRefParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cli ID ref params
func (o *GetCliIDRefParams) WithTimeout(timeout time.Duration) *GetCliIDRefParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cli ID ref params
func (o *GetCliIDRefParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cli ID ref params
func (o *GetCliIDRefParams) WithContext(ctx context.Context) *GetCliIDRefParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cli ID ref params
func (o *GetCliIDRefParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cli ID ref params
func (o *GetCliIDRefParams) WithHTTPClient(client *http.Client) *GetCliIDRefParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cli ID ref params
func (o *GetCliIDRefParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get cli ID ref params
func (o *GetCliIDRefParams) WithID(id string) *GetCliIDRefParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get cli ID ref params
func (o *GetCliIDRefParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCliIDRefParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
