// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostCliIDCallParams creates a new PostCliIDCallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCliIDCallParams() *PostCliIDCallParams {
	return &PostCliIDCallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCliIDCallParamsWithTimeout creates a new PostCliIDCallParams object
// with the ability to set a timeout on a request.
func NewPostCliIDCallParamsWithTimeout(timeout time.Duration) *PostCliIDCallParams {
	return &PostCliIDCallParams{
		timeout: timeout,
	}
}

// NewPostCliIDCallParamsWithContext creates a new PostCliIDCallParams object
// with the ability to set a context for a request.
func NewPostCliIDCallParamsWithContext(ctx context.Context) *PostCliIDCallParams {
	return &PostCliIDCallParams{
		Context: ctx,
	}
}

// NewPostCliIDCallParamsWithHTTPClient creates a new PostCliIDCallParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCliIDCallParamsWithHTTPClient(client *http.Client) *PostCliIDCallParams {
	return &PostCliIDCallParams{
		HTTPClient: client,
	}
}

/* PostCliIDCallParams contains all the parameters to send to the API endpoint
   for the post cli ID call operation.

   Typically these are written to a http.Request.
*/
type PostCliIDCallParams struct {

	/* Body.

	   Command execution parameters
	*/
	Body *models.CliCallRequest

	/* ID.

	   Command identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post cli ID call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCliIDCallParams) WithDefaults() *PostCliIDCallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post cli ID call params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCliIDCallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post cli ID call params
func (o *PostCliIDCallParams) WithTimeout(timeout time.Duration) *PostCliIDCallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post cli ID call params
func (o *PostCliIDCallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post cli ID call params
func (o *PostCliIDCallParams) WithContext(ctx context.Context) *PostCliIDCallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post cli ID call params
func (o *PostCliIDCallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post cli ID call params
func (o *PostCliIDCallParams) WithHTTPClient(client *http.Client) *PostCliIDCallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post cli ID call params
func (o *PostCliIDCallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post cli ID call params
func (o *PostCliIDCallParams) WithBody(body *models.CliCallRequest) *PostCliIDCallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post cli ID call params
func (o *PostCliIDCallParams) SetBody(body *models.CliCallRequest) {
	o.Body = body
}

// WithID adds the id to the post cli ID call params
func (o *PostCliIDCallParams) WithID(id string) *PostCliIDCallParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post cli ID call params
func (o *PostCliIDCallParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostCliIDCallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
