// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDatabasesParams creates a new GetDatabasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDatabasesParams() *GetDatabasesParams {
	return &GetDatabasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDatabasesParamsWithTimeout creates a new GetDatabasesParams object
// with the ability to set a timeout on a request.
func NewGetDatabasesParamsWithTimeout(timeout time.Duration) *GetDatabasesParams {
	return &GetDatabasesParams{
		timeout: timeout,
	}
}

// NewGetDatabasesParamsWithContext creates a new GetDatabasesParams object
// with the ability to set a context for a request.
func NewGetDatabasesParamsWithContext(ctx context.Context) *GetDatabasesParams {
	return &GetDatabasesParams{
		Context: ctx,
	}
}

// NewGetDatabasesParamsWithHTTPClient creates a new GetDatabasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDatabasesParamsWithHTTPClient(client *http.Client) *GetDatabasesParams {
	return &GetDatabasesParams{
		HTTPClient: client,
	}
}

/* GetDatabasesParams contains all the parameters to send to the API endpoint
   for the get databases operation.

   Typically these are written to a http.Request.
*/
type GetDatabasesParams struct {

	/* Domain.

	   Filter data by domain name
	*/
	Domain *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDatabasesParams) WithDefaults() *GetDatabasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDatabasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get databases params
func (o *GetDatabasesParams) WithTimeout(timeout time.Duration) *GetDatabasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get databases params
func (o *GetDatabasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get databases params
func (o *GetDatabasesParams) WithContext(ctx context.Context) *GetDatabasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get databases params
func (o *GetDatabasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get databases params
func (o *GetDatabasesParams) WithHTTPClient(client *http.Client) *GetDatabasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get databases params
func (o *GetDatabasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the get databases params
func (o *GetDatabasesParams) WithDomain(domain *string) *GetDatabasesParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the get databases params
func (o *GetDatabasesParams) SetDomain(domain *string) {
	o.Domain = domain
}

// WriteToRequest writes these params to a swagger request
func (o *GetDatabasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Domain != nil {

		// query param domain
		var qrDomain string

		if o.Domain != nil {
			qrDomain = *o.Domain
		}
		qDomain := qrDomain
		if qDomain != "" {

			if err := r.SetQueryParam("domain", qDomain); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
