// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDbserversParams creates a new GetDbserversParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDbserversParams() *GetDbserversParams {
	return &GetDbserversParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDbserversParamsWithTimeout creates a new GetDbserversParams object
// with the ability to set a timeout on a request.
func NewGetDbserversParamsWithTimeout(timeout time.Duration) *GetDbserversParams {
	return &GetDbserversParams{
		timeout: timeout,
	}
}

// NewGetDbserversParamsWithContext creates a new GetDbserversParams object
// with the ability to set a context for a request.
func NewGetDbserversParamsWithContext(ctx context.Context) *GetDbserversParams {
	return &GetDbserversParams{
		Context: ctx,
	}
}

// NewGetDbserversParamsWithHTTPClient creates a new GetDbserversParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDbserversParamsWithHTTPClient(client *http.Client) *GetDbserversParams {
	return &GetDbserversParams{
		HTTPClient: client,
	}
}

/* GetDbserversParams contains all the parameters to send to the API endpoint
   for the get dbservers operation.

   Typically these are written to a http.Request.
*/
type GetDbserversParams struct {

	/* ID.

	   Filter data by database server id
	*/
	ID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dbservers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbserversParams) WithDefaults() *GetDbserversParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dbservers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbserversParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dbservers params
func (o *GetDbserversParams) WithTimeout(timeout time.Duration) *GetDbserversParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dbservers params
func (o *GetDbserversParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dbservers params
func (o *GetDbserversParams) WithContext(ctx context.Context) *GetDbserversParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dbservers params
func (o *GetDbserversParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dbservers params
func (o *GetDbserversParams) WithHTTPClient(client *http.Client) *GetDbserversParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dbservers params
func (o *GetDbserversParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get dbservers params
func (o *GetDbserversParams) WithID(id *int64) *GetDbserversParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dbservers params
func (o *GetDbserversParams) SetID(id *int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDbserversParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID int64

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatInt64(qrID)
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
