// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// GetDatabasesReader is a Reader for the GetDatabases structure.
type GetDatabasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatabasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDatabasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDatabasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDatabasesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDatabasesOK creates a GetDatabasesOK with default headers values
func NewGetDatabasesOK() *GetDatabasesOK {
	return &GetDatabasesOK{}
}

/* GetDatabasesOK describes a response with status code 200, with default header values.

OK
*/
type GetDatabasesOK struct {
	Payload []*models.Database
}

func (o *GetDatabasesOK) Error() string {
	return fmt.Sprintf("[GET /databases][%d] getDatabasesOK  %+v", 200, o.Payload)
}
func (o *GetDatabasesOK) GetPayload() []*models.Database {
	return o.Payload
}

func (o *GetDatabasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatabasesBadRequest creates a GetDatabasesBadRequest with default headers values
func NewGetDatabasesBadRequest() *GetDatabasesBadRequest {
	return &GetDatabasesBadRequest{}
}

/* GetDatabasesBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type GetDatabasesBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetDatabasesBadRequest) Error() string {
	return fmt.Sprintf("[GET /databases][%d] getDatabasesBadRequest  %+v", 400, o.Payload)
}
func (o *GetDatabasesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDatabasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatabasesNotFound creates a GetDatabasesNotFound with default headers values
func NewGetDatabasesNotFound() *GetDatabasesNotFound {
	return &GetDatabasesNotFound{}
}

/* GetDatabasesNotFound describes a response with status code 404, with default header values.

Server is not found
*/
type GetDatabasesNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetDatabasesNotFound) Error() string {
	return fmt.Sprintf("[GET /databases][%d] getDatabasesNotFound  %+v", 404, o.Payload)
}
func (o *GetDatabasesNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDatabasesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
