// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDbusersParams creates a new GetDbusersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDbusersParams() *GetDbusersParams {
	return &GetDbusersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDbusersParamsWithTimeout creates a new GetDbusersParams object
// with the ability to set a timeout on a request.
func NewGetDbusersParamsWithTimeout(timeout time.Duration) *GetDbusersParams {
	return &GetDbusersParams{
		timeout: timeout,
	}
}

// NewGetDbusersParamsWithContext creates a new GetDbusersParams object
// with the ability to set a context for a request.
func NewGetDbusersParamsWithContext(ctx context.Context) *GetDbusersParams {
	return &GetDbusersParams{
		Context: ctx,
	}
}

// NewGetDbusersParamsWithHTTPClient creates a new GetDbusersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDbusersParamsWithHTTPClient(client *http.Client) *GetDbusersParams {
	return &GetDbusersParams{
		HTTPClient: client,
	}
}

/* GetDbusersParams contains all the parameters to send to the API endpoint
   for the get dbusers operation.

   Typically these are written to a http.Request.
*/
type GetDbusersParams struct {

	/* DbID.

	   Filter data by database ID
	*/
	DbID *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dbusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbusersParams) WithDefaults() *GetDbusersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dbusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDbusersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dbusers params
func (o *GetDbusersParams) WithTimeout(timeout time.Duration) *GetDbusersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dbusers params
func (o *GetDbusersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dbusers params
func (o *GetDbusersParams) WithContext(ctx context.Context) *GetDbusersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dbusers params
func (o *GetDbusersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dbusers params
func (o *GetDbusersParams) WithHTTPClient(client *http.Client) *GetDbusersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dbusers params
func (o *GetDbusersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDbID adds the dbID to the get dbusers params
func (o *GetDbusersParams) WithDbID(dbID *int64) *GetDbusersParams {
	o.SetDbID(dbID)
	return o
}

// SetDbID adds the dbId to the get dbusers params
func (o *GetDbusersParams) SetDbID(dbID *int64) {
	o.DbID = dbID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDbusersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DbID != nil {

		// query param dbId
		var qrDbID int64

		if o.DbID != nil {
			qrDbID = *o.DbID
		}
		qDbID := swag.FormatInt64(qrDbID)
		if qDbID != "" {

			if err := r.SetQueryParam("dbId", qDbID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
