// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// NewPostDbusersParams creates a new PostDbusersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDbusersParams() *PostDbusersParams {
	return &PostDbusersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDbusersParamsWithTimeout creates a new PostDbusersParams object
// with the ability to set a timeout on a request.
func NewPostDbusersParamsWithTimeout(timeout time.Duration) *PostDbusersParams {
	return &PostDbusersParams{
		timeout: timeout,
	}
}

// NewPostDbusersParamsWithContext creates a new PostDbusersParams object
// with the ability to set a context for a request.
func NewPostDbusersParamsWithContext(ctx context.Context) *PostDbusersParams {
	return &PostDbusersParams{
		Context: ctx,
	}
}

// NewPostDbusersParamsWithHTTPClient creates a new PostDbusersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDbusersParamsWithHTTPClient(client *http.Client) *PostDbusersParams {
	return &PostDbusersParams{
		HTTPClient: client,
	}
}

/* PostDbusersParams contains all the parameters to send to the API endpoint
   for the post dbusers operation.

   Typically these are written to a http.Request.
*/
type PostDbusersParams struct {

	/* Body.

	   Database User data
	*/
	Body *models.DatabaseUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post dbusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDbusersParams) WithDefaults() *PostDbusersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post dbusers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDbusersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post dbusers params
func (o *PostDbusersParams) WithTimeout(timeout time.Duration) *PostDbusersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post dbusers params
func (o *PostDbusersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post dbusers params
func (o *PostDbusersParams) WithContext(ctx context.Context) *PostDbusersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post dbusers params
func (o *PostDbusersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post dbusers params
func (o *PostDbusersParams) WithHTTPClient(client *http.Client) *PostDbusersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post dbusers params
func (o *PostDbusersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post dbusers params
func (o *PostDbusersParams) WithBody(body *models.DatabaseUserRequest) *PostDbusersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post dbusers params
func (o *PostDbusersParams) SetBody(body *models.DatabaseUserRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDbusersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
