// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/jxsl13/plesgo/models"
)

// NewPutDbusersIDParams creates a new PutDbusersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutDbusersIDParams() *PutDbusersIDParams {
	return &PutDbusersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutDbusersIDParamsWithTimeout creates a new PutDbusersIDParams object
// with the ability to set a timeout on a request.
func NewPutDbusersIDParamsWithTimeout(timeout time.Duration) *PutDbusersIDParams {
	return &PutDbusersIDParams{
		timeout: timeout,
	}
}

// NewPutDbusersIDParamsWithContext creates a new PutDbusersIDParams object
// with the ability to set a context for a request.
func NewPutDbusersIDParamsWithContext(ctx context.Context) *PutDbusersIDParams {
	return &PutDbusersIDParams{
		Context: ctx,
	}
}

// NewPutDbusersIDParamsWithHTTPClient creates a new PutDbusersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutDbusersIDParamsWithHTTPClient(client *http.Client) *PutDbusersIDParams {
	return &PutDbusersIDParams{
		HTTPClient: client,
	}
}

/* PutDbusersIDParams contains all the parameters to send to the API endpoint
   for the put dbusers ID operation.

   Typically these are written to a http.Request.
*/
type PutDbusersIDParams struct {

	/* Body.

	   Database user data
	*/
	Body *models.DatabaseUserUpdateRequest

	/* ID.

	   Database user ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put dbusers ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDbusersIDParams) WithDefaults() *PutDbusersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put dbusers ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDbusersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put dbusers ID params
func (o *PutDbusersIDParams) WithTimeout(timeout time.Duration) *PutDbusersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put dbusers ID params
func (o *PutDbusersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put dbusers ID params
func (o *PutDbusersIDParams) WithContext(ctx context.Context) *PutDbusersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put dbusers ID params
func (o *PutDbusersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put dbusers ID params
func (o *PutDbusersIDParams) WithHTTPClient(client *http.Client) *PutDbusersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put dbusers ID params
func (o *PutDbusersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put dbusers ID params
func (o *PutDbusersIDParams) WithBody(body *models.DatabaseUserUpdateRequest) *PutDbusersIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put dbusers ID params
func (o *PutDbusersIDParams) SetBody(body *models.DatabaseUserUpdateRequest) {
	o.Body = body
}

// WithID adds the id to the put dbusers ID params
func (o *PutDbusersIDParams) WithID(id int64) *PutDbusersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put dbusers ID params
func (o *PutDbusersIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutDbusersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
