// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jxsl13/plesgo/models"
)

// PutDbusersIDReader is a Reader for the PutDbusersID structure.
type PutDbusersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDbusersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutDbusersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutDbusersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutDbusersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutDbusersIDOK creates a PutDbusersIDOK with default headers values
func NewPutDbusersIDOK() *PutDbusersIDOK {
	return &PutDbusersIDOK{}
}

/* PutDbusersIDOK describes a response with status code 200, with default header values.

OK
*/
type PutDbusersIDOK struct {
	Payload *models.StatusResponse
}

func (o *PutDbusersIDOK) Error() string {
	return fmt.Sprintf("[PUT /dbusers/{id}][%d] putDbusersIdOK  %+v", 200, o.Payload)
}
func (o *PutDbusersIDOK) GetPayload() *models.StatusResponse {
	return o.Payload
}

func (o *PutDbusersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDbusersIDBadRequest creates a PutDbusersIDBadRequest with default headers values
func NewPutDbusersIDBadRequest() *PutDbusersIDBadRequest {
	return &PutDbusersIDBadRequest{}
}

/* PutDbusersIDBadRequest describes a response with status code 400, with default header values.

Invalid request data
*/
type PutDbusersIDBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutDbusersIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /dbusers/{id}][%d] putDbusersIdBadRequest  %+v", 400, o.Payload)
}
func (o *PutDbusersIDBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutDbusersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutDbusersIDNotFound creates a PutDbusersIDNotFound with default headers values
func NewPutDbusersIDNotFound() *PutDbusersIDNotFound {
	return &PutDbusersIDNotFound{}
}

/* PutDbusersIDNotFound describes a response with status code 404, with default header values.

Server/database/domain is not found
*/
type PutDbusersIDNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PutDbusersIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /dbusers/{id}][%d] putDbusersIdNotFound  %+v", 404, o.Payload)
}
func (o *PutDbusersIDNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutDbusersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
