// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CliCallRequest Command execution parameters
//
// swagger:model CliCallRequest
type CliCallRequest struct {

	// env
	// Example: {"PSA_PASSWORD":"password"}
	Env interface{} `json:"env,omitempty"`

	// params
	// Example: ["--get","FullHostName"]
	Params []string `json:"params"`
}

// Validate validates this cli call request
func (m *CliCallRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cli call request based on context it is used
func (m *CliCallRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CliCallRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CliCallRequest) UnmarshalBinary(b []byte) error {
	var res CliCallRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
