// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Client The client entity
//
// swagger:model Client
type Client struct {

	// The company name (0 to 60 characters long).
	// Example: Plesk
	// Required: true
	Company *string `json:"company"`

	// Creation date.
	// Example: 2016-11-13
	// Required: true
	// Format: date
	Created *strfmt.Date `json:"created"`

	// The description for the client account.
	// Example: Nice guy
	// Required: true
	Description *string `json:"description"`

	// The email address of the client account owner (0 to 255 characters long).
	// Example: john_smith@msn.com
	// Required: true
	Email *string `json:"email"`

	// The client GUID in the Plesk components (for example, Business Manager).
	// Example: link:12345
	ExternalID string `json:"external_id,omitempty"`

	// The global user ID of the client account just added to Plesk.
	// Example: 18b78dd1-2b43-44f7-9599-56ccb56a85dc
	// Required: true
	GUID *string `json:"guid"`

	// The client's ID.
	// Example: 7
	// Required: true
	ID *int64 `json:"id"`

	// The locale used on the client account. Default value: en-US.
	// Example: en-US
	// Required: true
	Locale *string `json:"locale"`

	// The login name of the client account (1 to 60 characters long).
	// Example: john-unit-test
	// Required: true
	Login *string `json:"login"`

	// Client's personal name (1 to 60 characters long).
	// Example: John Smith
	// Required: true
	Name *string `json:"name"`

	// The login name of a client account owner. If the client account owner is Plesk Administrator, specify the admin login name.
	// Example: admin
	OwnerLogin string `json:"owner_login,omitempty"`

	// The current status of the client account. Allowed values: 0 (active) | 16 (disabled by admin) | 4 (under backup/restore) | 256 (expired).
	// Example: 0
	// Required: true
	Status *int64 `json:"status"`

	// The type of the client account. Allowed values: reseller | customer | admin.
	// Example: reseller
	// Required: true
	// Enum: [reseller customer admin]
	Type *string `json:"type"`
}

// Validate validates this client
func (m *Client) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompany(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Client) validateCompany(formats strfmt.Registry) error {

	if err := validate.Required("company", "body", m.Company); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", m.Created); err != nil {
		return err
	}

	if err := validate.FormatOf("created", "body", "date", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateGUID(formats strfmt.Registry) error {

	if err := validate.Required("guid", "body", m.GUID); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateLocale(formats strfmt.Registry) error {

	if err := validate.Required("locale", "body", m.Locale); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Client) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

var clientTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["reseller","customer","admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clientTypeTypePropEnum = append(clientTypeTypePropEnum, v)
	}
}

const (

	// ClientTypeReseller captures enum value "reseller"
	ClientTypeReseller string = "reseller"

	// ClientTypeCustomer captures enum value "customer"
	ClientTypeCustomer string = "customer"

	// ClientTypeAdmin captures enum value "admin"
	ClientTypeAdmin string = "admin"
)

// prop value enum
func (m *Client) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, clientTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Client) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this client based on context it is used
func (m *Client) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Client) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Client) UnmarshalBinary(b []byte) error {
	var res Client
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
