// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClientUpdateRequest The client entity
//
// swagger:model ClientUpdateRequest
type ClientUpdateRequest struct {

	// The company name (0 to 60 characters long).
	// Example: Plesk
	Company string `json:"company,omitempty"`

	// The description for the client account.
	// Example: Nice guy
	Description string `json:"description,omitempty"`

	// The email address of the client account owner (0 to 255 characters long).
	// Example: john_smith@msn.com
	Email string `json:"email,omitempty"`

	// The client GUID in the Plesk components (for example, Business Manager).
	// Example: link:12345
	ExternalID string `json:"external_id,omitempty"`

	// The locale used on the client account. Default value: en-US.
	// Example: en-US
	Locale string `json:"locale,omitempty"`

	// The login name of the client account (1 to 60 characters long).
	// Example: john-unit-test
	Login string `json:"login,omitempty"`

	// Client's personal name (1 to 60 characters long).
	// Example: John Smith
	Name string `json:"name,omitempty"`

	// The login name of a client account owner. If the client account owner is Plesk Administrator, specify the admin login name.
	// Example: admin
	OwnerLogin string `json:"owner_login,omitempty"`

	// The password of the client account (5 to 14 characters long).
	// Example: changeme1Q**
	Password string `json:"password,omitempty"`

	// The current status of the client account. Allowed values: 0 (active) | 16 (disabled by admin) | 4 (under backup/restore) | 256 (expired).
	// Example: 0
	Status int64 `json:"status,omitempty"`
}

// Validate validates this client update request
func (m *ClientUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this client update request based on context it is used
func (m *ClientUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClientUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientUpdateRequest) UnmarshalBinary(b []byte) error {
	var res ClientUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
