// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FtpUser ftp user
//
// swagger:model FtpUser
type FtpUser struct {

	// Subdirectory of the WWW Root that user is restricted to
	// Example: /httpdocs
	// Required: true
	Home *string `json:"home"`

	// User ID in the database
	// Example: 2
	// Required: true
	ID *int64 `json:"id"`

	// User name in the system
	// Example: exampleuser
	// Required: true
	Name *string `json:"name"`

	// ID of the parent domain
	// Example: 4
	// Required: true
	ParentDomain *int64 `json:"parent_domain"`

	// permissions
	Permissions *FtpUserPermissions `json:"permissions,omitempty"`

	// Hard disk quota in bytes (if supported by platform)
	// Example: -1
	Quota int64 `json:"quota,omitempty"`
}

// Validate validates this ftp user
func (m *FtpUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHome(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePermissions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FtpUser) validateHome(formats strfmt.Registry) error {

	if err := validate.Required("home", "body", m.Home); err != nil {
		return err
	}

	return nil
}

func (m *FtpUser) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *FtpUser) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *FtpUser) validateParentDomain(formats strfmt.Registry) error {

	if err := validate.Required("parent_domain", "body", m.ParentDomain); err != nil {
		return err
	}

	return nil
}

func (m *FtpUser) validatePermissions(formats strfmt.Registry) error {
	if swag.IsZero(m.Permissions) { // not required
		return nil
	}

	if m.Permissions != nil {
		if err := m.Permissions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("permissions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("permissions")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ftp user based on the context it is used
func (m *FtpUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePermissions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FtpUser) contextValidatePermissions(ctx context.Context, formats strfmt.Registry) error {

	if m.Permissions != nil {
		if err := m.Permissions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("permissions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("permissions")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FtpUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FtpUser) UnmarshalBinary(b []byte) error {
	var res FtpUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FtpUserPermissions Access permissions of the user (if supported by platform)
//
// swagger:model FtpUserPermissions
type FtpUserPermissions struct {

	// read
	// Enum: [true false]
	Read string `json:"read,omitempty"`

	// write
	// Enum: [true false]
	Write string `json:"write,omitempty"`
}

// Validate validates this ftp user permissions
func (m *FtpUserPermissions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRead(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWrite(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var ftpUserPermissionsTypeReadPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["true","false"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ftpUserPermissionsTypeReadPropEnum = append(ftpUserPermissionsTypeReadPropEnum, v)
	}
}

const (

	// FtpUserPermissionsReadTrue captures enum value "true"
	FtpUserPermissionsReadTrue string = "true"

	// FtpUserPermissionsReadFalse captures enum value "false"
	FtpUserPermissionsReadFalse string = "false"
)

// prop value enum
func (m *FtpUserPermissions) validateReadEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, ftpUserPermissionsTypeReadPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FtpUserPermissions) validateRead(formats strfmt.Registry) error {
	if swag.IsZero(m.Read) { // not required
		return nil
	}

	// value enum
	if err := m.validateReadEnum("permissions"+"."+"read", "body", m.Read); err != nil {
		return err
	}

	return nil
}

var ftpUserPermissionsTypeWritePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["true","false"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ftpUserPermissionsTypeWritePropEnum = append(ftpUserPermissionsTypeWritePropEnum, v)
	}
}

const (

	// FtpUserPermissionsWriteTrue captures enum value "true"
	FtpUserPermissionsWriteTrue string = "true"

	// FtpUserPermissionsWriteFalse captures enum value "false"
	FtpUserPermissionsWriteFalse string = "false"
)

// prop value enum
func (m *FtpUserPermissions) validateWriteEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, ftpUserPermissionsTypeWritePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FtpUserPermissions) validateWrite(formats strfmt.Registry) error {
	if swag.IsZero(m.Write) { // not required
		return nil
	}

	// value enum
	if err := m.validateWriteEnum("permissions"+"."+"write", "body", m.Write); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ftp user permissions based on context it is used
func (m *FtpUserPermissions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FtpUserPermissions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FtpUserPermissions) UnmarshalBinary(b []byte) error {
	var res FtpUserPermissions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
