// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerInit Initial server setup parameters
//
// swagger:model ServerInit
type ServerInit struct {

	// admin
	// Required: true
	Admin *Admin `json:"admin"`

	// The new Plesk Administrator's password that will replace the default one.
	// Example: setup
	// Required: true
	Password *string `json:"password"`

	// The full host name.
	// Example: my-plesk-server.com
	ServerName string `json:"server_name,omitempty"`
}

// Validate validates this server init
func (m *ServerInit) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerInit) validateAdmin(formats strfmt.Registry) error {

	if err := validate.Required("admin", "body", m.Admin); err != nil {
		return err
	}

	if m.Admin != nil {
		if err := m.Admin.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("admin")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("admin")
			}
			return err
		}
	}

	return nil
}

func (m *ServerInit) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this server init based on the context it is used
func (m *ServerInit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdmin(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerInit) contextValidateAdmin(ctx context.Context, formats strfmt.Registry) error {

	if m.Admin != nil {
		if err := m.Admin.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("admin")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("admin")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServerInit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerInit) UnmarshalBinary(b []byte) error {
	var res ServerInit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
